-- Generated by Oracle SQL Developer Data Modeler 22.2.0.165.1149
--   at:        2022-08-31 23:22:28 CST
--   site:      SQL Server 2012
--   type:      SQL Server 2012

USE P1_201908338;

CREATE TABLE Categoria 
    (
     id_categoria INTEGER NOT NULL , 
     nombre VARCHAR (50) ,
     CONSTRAINT Categoria_PK PRIMARY KEY CLUSTERED (id_categoria)
    );

CREATE TABLE Cliente 
    (
     id_cliente INTEGER NOT NULL , 
     Nombre VARCHAR (50) , 
     Apellido VARCHAR (50) , 
     Direccion VARCHAR (60) , 
     Telefono VARCHAR (50) , 
     Tarjeta VARCHAR (50) , 
     Edad INTEGER , 
     Salario INTEGER , 
     Genero CHAR (1) , 
     Pais_id_pais INTEGER NOT NULL ,
     CONSTRAINT Cliente_PK PRIMARY KEY CLUSTERED (id_cliente)
    );

CREATE TABLE Detalle 
    (
     id_detalle INTEGER AUTO_INCREMENT NOT NULL , 
     linea_orden INTEGER , 
     cantidad INTEGER , 
     Vendedor_id_vendedor INTEGER NOT NULL , 
     Producto_id_producto INTEGER NOT NULL , 
     Orden_id_orden INTEGER NOT NULL ,
     CONSTRAINT Detalle_PK PRIMARY KEY CLUSTERED (id_detalle)
    );

CREATE TABLE Orden 
    (
     id_orden INTEGER NOT NULL AUTO_INCREMENT, 
     fecha_orden DATE , 
     Cliente_id_cliente INTEGER NOT NULL ,
     CONSTRAINT Orden_PK PRIMARY KEY CLUSTERED (id_orden)
    );

CREATE TABLE Pais 
    (
     id_pais INTEGER NOT NULL , 
     nombre VARCHAR (50) ,
     CONSTRAINT Pais_PK PRIMARY KEY CLUSTERED (id_pais)
    );

CREATE TABLE Producto 
    (
     id_producto INTEGER NOT NULL , 
     Nombre VARCHAR (50) NOT NULL , 
     Precio FLOAT (2) , 
     Categoria_id_categoria INTEGER NOT NULL ,
     CONSTRAINT Producto_PK PRIMARY KEY CLUSTERED (id_producto)
    );

CREATE TABLE Vendedor 
    (
     id_vendedor INTEGER NOT NULL , 
     nombre VARCHAR (50) , 
     Pais_id_pais INTEGER NOT NULL ,
     CONSTRAINT Vendedor_PK PRIMARY KEY CLUSTERED (id_vendedor)
    );

ALTER TABLE Cliente 
    ADD CONSTRAINT Cliente_Pais_FK FOREIGN KEY 
    ( 
     Pais_id_pais
    ) 
    REFERENCES Pais 
    ( 
     id_pais 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;

ALTER TABLE Detalle 
    ADD CONSTRAINT Detalle_Orden_FK FOREIGN KEY 
    ( 
     Orden_id_orden
    ) 
    REFERENCES Orden 
    ( 
     id_orden 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;

ALTER TABLE Detalle 
    ADD CONSTRAINT Detalle_Producto_FK FOREIGN KEY 
    ( 
     Producto_id_producto
    ) 
    REFERENCES Producto 
    ( 
     id_producto 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;

ALTER TABLE Detalle 
    ADD CONSTRAINT Detalle_Vendedor_FK FOREIGN KEY 
    ( 
     Vendedor_id_vendedor
    ) 
    REFERENCES Vendedor 
    ( 
     id_vendedor 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;

ALTER TABLE Orden 
    ADD CONSTRAINT Orden_Cliente_FK FOREIGN KEY 
    ( 
     Cliente_id_cliente
    ) 
    REFERENCES Cliente 
    ( 
     id_cliente 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;

ALTER TABLE Producto 
    ADD CONSTRAINT Producto_Categoria_FK FOREIGN KEY 
    ( 
     Categoria_id_categoria
    ) 
    REFERENCES Categoria 
    ( 
     id_categoria 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;

ALTER TABLE Vendedor 
    ADD CONSTRAINT Vendedor_Pais_FK FOREIGN KEY 
    ( 
     Pais_id_pais
    ) 
    REFERENCES Pais 
    ( 
     id_pais 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION ;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             0
-- ALTER TABLE                             14
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE SCHEMA                            0
-- CREATE SEQUENCE                          0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0


SELECT * FROM Cliente;
SELECT * FROM Pais;
SELECT * FROM Orden;
SELECT * FROM Detalle;
SELECT * FROM Vendedor;
SELECT * FROM Producto;
SELECT * FROM Categoria ;
SELECT * FROM AUX;

DROP TABLE AUX;

CREATE TABLE AUX 
    (
     id_orden INTEGER , 
     linea_orden INTEGER , 
     fecha_orden DATE , 
     Cliente_id_cliente INTEGER NOT NULL ,
     Vendedor_id_vendedor INTEGER NOT NULL , 
     Producto_id_producto INTEGER NOT NULL , 
     cantidad INTEGER 
    );
